absen_SQLite/absen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

# gambar/static
from django.conf import settings 
from django.conf.urls.static import static 

#url/alamat per halaman 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='home'),
    path('akun',views.akun, name='akun'),
    path('absen/',include('absenapp.urls', namespace='absen'  ) ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

absen_SQLite/absenapp/urls.py
from django.urls import path
from . import views

# utntuk menyambungkan/include url pada menu/app dengan project
app_name='absenapp'

#url/alamat per halaman 
urlpatterns =[
    path('',views.absen, name='absen'),
    path('profile/',views.profile, name='profile'),
    path('register/',views.register, name='register'),
    path('login/',views.loginAkun, name='login'),
    path('logoutAkun/',views.logoutAkun, name='logout'),
]

absen_SQLite/absenapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# tabel untuk profile karyawan
class profil(models.Model):
    nama        =models.OneToOneField(User, on_delete=models.CASCADE, related_name='profil')
    nip         =models.CharField(max_length=50, default='-')
    jk =(
        ('Laki-Laki','L'),
        ('Perempuan','P'),
    )
    jenisK      =models.CharField(choices=jk, max_length=10)
    jabatan     =models.CharField(max_length=50,null=True)
    alamat      =models.TextField()
    

    def __str__(self):
        return "{}".format(self.nama)

# tabel utnuk absen karyawan
class absenModel(models.Model):
    # data karyawan    
    pegawai     =models.ForeignKey(profil, on_delete=models.DO_NOTHING)
    tgl         =models.DateField(auto_now_add=True)
    waktu       =models.TimeField(auto_now_add=True)
    absen=(
        ('HADIR','HADIR'),
        ('IZIN','IZIN'),
        ('PULANG','PULANG'),
    )
    status      =models.CharField(choices=absen, max_length=50, default='HADIR')
    ket         =models.TextField(null=True, blank=True) 

    def __str__(self):
        return "{}".format(self.pegawai)

absen_SQLite/absenapp/forms.py
from django import forms
from . models import absenModel,profil

# form untuk profil karyawan
class profilForm(forms.ModelForm):
    class Meta():
        model=profil #nama tabel
        fields="__all__" #ambil semu kolom
        
        # untuk merubah/ganti nama label 
        labels= {
            'jenisK' : 'Jenis Kelamin',
        }

        # untuk styling form
        widgets={
            'nama':forms.Select(
                attrs={
                    'class':'form-control',}
                ),
            'nip':forms.TextInput(
                attrs={
                    'class':'form-control',}
                ),
            'jenisK':forms.Select(
                attrs={
                    'class':'form-control',
                    'label':'Jenis Kelamin'}
                ),
            'jabatan':forms.TextInput(
                attrs={
                    'class':'form-control',}
                ),
            'alamat':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'style':'height: 80px;',}
                ),
            }

# form untuk absen
class absenForm(forms.ModelForm):
    class Meta:
        model = absenModel
        fields = [
                # 'pegawai',
                'status',
                'ket',      
            ]
        widgets={
            # 'pegawai':forms.TextInput(
            #     attrs={
            #         'class':'form-control',}
            #     ),
            'status':forms.Select(
                attrs={
                    'class':'form-control',}
                ),
            'ket':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'style':'height: 80px;',}
                ),
            }

absen_SQLite/absen/views.py
from django.shortcuts import render,redirect
from absenapp . models import absenModel,profil
from django.contrib.auth import authenticate
from django.contrib import messages
from django.core.paginator import Paginator

def akun(request):
    if request.user.is_active:
        # ambil nama berdasarkan user yang aktif dari tabel profil -> (1 jenis data yaitu nama)
        profile=profil.objects.get(nama=request.user)

        # ambil data pegawai berdasarkan user yang aktif (profil) dari tabel absenmodel ->(semua data)
        datas= absenModel.objects.filter(pegawai=profile)

        # inisialiasi jumlah status: hadir,izin dan pulang
        jh=0
        ji=0
        jp=0
        # untuk mendaptkan jumlah sesuai status maka setiap kali melakukan absen akan di jumlahkan sesuai dengan statusnya
        for jlh in datas:
            if jlh.status == 'HADIR': #jika status absennya hadir maka variabel inisialisasi kita jumlahkan
                jh += 1
            elif jlh.status == 'IZIN':
                ji += 1
            elif jlh.status == 'PULANG':
                jp += 1
            else:
                pass
        #paginator
        data = datas.order_by('-tgl')
        hal = Paginator(data,5)
        hal_list = request.GET.get('page')
        datas = hal.get_page(hal_list)
    else:
        return redirect('absen:login')

    context = {
        'datas':datas,
        'jlh_hadir':jh,
        'jlh_izin':ji,
        'jlh_pulang':jp,
    }

    return render(request,'akun.html',context)

def index(request):

    return render(request, 'index.html')

absen_SQLite/absenapp/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from absenapp . models import absenModel,profil
from .forms import profilForm,absenForm
from django.contrib import messages

# @login_required() #fungsi ini bisa diakses setelah login berhasil
def absen(request):

    if request.user.is_active:
        data = absenModel.objects.all() #ambil semua data di tabel absenmodel
        ab = absenForm() 
        pgaw = profil.objects.get(nama=request.user)

        if request.method == 'POST':
            absenModel.objects.create(
                pegawai = pgaw,
                status  = request.POST.get('status'),
                ket     = request.POST.get('ket'),
            )

            messages.success(request,"Selamat Absen Berhasil")
            return redirect('akun')
    else:
        return redirect('absen:login')

    #lempar data yang sudah didapat ke templates
  
    context = { 
        'profile':ab,
        'datas':data,
    }
    return render(request, 'absen.html',context)

def profile(request):

    karyawan=profilForm(request.POST or None)
    if request.method == 'POST':
        if karyawan.is_valid():
            karyawan.save()
        return redirect('absen:login')

    context = {
        'karyawan':karyawan,
    }
    return render(request,'profile.html', context)

# AKUN
def register(request):
    if request.method=='POST':
        username=request.POST.get('username') #megambil data dari form username
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')

        if pass1!=pass2: #jika password/password 1 tidak sama dengan confirm password atau password ke 2
            messages.warning(request, 'Password tidak sama!')
            return redirect('absen:register') #ke halaman register
        else: #jika sama password 1 dengan ke 2
            my_user=User.objects.create_user(username,email,pass1) #buat user baru dengan data username,email dan password
            my_user.save()
            messages.success(request,"Selamat Register Berhasil")
            return redirect('absen:profile') #ke halaman login

    return render(request,'register.html')

def loginAkun(request):
    if request.method=='POST':
        username=request.POST.get('username')
        pass1=request.POST.get('passw')

        user=authenticate(request,username=username,password=pass1) #cek username dan password
        if user is not None: #jika username dan password ada di database maka
            login(request, user) 
            
            if user.is_superuser: #jika user adalah admin maka tampilkan halaman ad  min
                return redirect('/admin/')
            else: #jika user bukan admin maka tampilkan halaman absen
                messages.success(request,"Selamat, Login Berhasil!")  
                return redirect('akun')

        else:# jika username dan password  tidak ada
            messages.warning(request,'Username dan Password tidak Valid!!')
            return redirect('absen:login') #ke halaman login
    return render(request,'login.html')

def logoutAkun(request):
    logout(request) 
    return redirect('absen:login')

absen_SQLite/templates/absen.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">
    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <title>AbsensiOnline</title>
  </head>
  <body>
    <div class="row" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
        <div class="container py-5 text-center">
            <div class="row">
                <div class="col-12">
                    <div class="row py-lg-5">
                        <div class="col-lg-6 col-md-8 mx-auto">
                            <div class="card">
                                <div class="card-body py-4 px-md-5" style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                                  {%for message in messages%} 
                                  {%if message.tags == 'warning'%}
                                  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                                    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                  </symbol>
                                  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                                  </symbol>
                                  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                  </symbol>
                                  </svg>
                                  <div class="alert alert-danger d-flex align-items-center" role="alert">
                                    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                                    <div>
                                      {{message}}
                                    </div>
                                  </div>
                                  {%endif%}
                                  {%endfor%}  
                                  
                                  <form class="my-3" method="POST" >
                                      {%csrf_token%}                                       
                                        <div class="row">
                                        <div class="col-12 mb-4">
                                            <div class="form-outline text-center">
                                            <h1>Hai...👋🏻{{user}}, Absen!</h1>
                                            <h6 id="waktu"></h6>                                                                                                          
                                          </div>
                                        </div>                         
                                        </div>

                                        <!-- Email input -->
                                        {%for form in profile %}
                                        <div class="form-group form-outline mb-4 text-start">
                                            {{form.label}}
                                            {{form}}
                                        </div>
                                        {%endfor%}
        
                                        <!-- Submit button -->
                                        <button type="submit" class="btn btn-primary mb-4" style="width: 100%;" >
                                        Absen
                                        </button>

                                        <!-- Register buttons -->
                                        <div class="text-center">
                                        <p>Kembali ke halaman<a href="{%url 'absen:profile'%}" class="text-primary">Profile</a></p>
                                        <a href="/" class="text-dark" style="text-decoration: none;">Kembali ke Halaman <span class="fw-bold">Home</span></a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-5 text-white" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 

    <!-- waktu -->
    <script>
      let waktu = document.getElementById("waktu");
      setInterval(() => {
          let jam  = new Date();
          waktu.innerHTML = jam.toLocaleTimeString();
        },100
      )
     
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{%static 'js/bootstrap.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
  </body>
</html>

absen_SQLite/templates/akun.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">
    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <title>AbsensiOnline | Absen </title>
  </head>
  <body>
    <!-- header -->
    <div class="row" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-6">
        <div class="container text-white pt-4" style="height: 450px;">
          <div class="head ps-5 pt-5" style="margin: 50px auto;" >
            <h1 class=""> Hai...👋🏻<a class="text-primary" href="/" style="text-decoration: none;">{{user}}</a> Selamat Datang</h1>
            <p class="pe-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.Blanditiis corporis, adipisci  
              accusantium,Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>
              saepe dignissimos a ut ex facilis inventore!</p>
            <a href="{%url 'absen:absen'%} " class="btn btn-primary" style="height: 40px; width: 120px;"> Absensi </a>
            <a href="{% url 'absen:logout'%}" class="btn btn-outline-primary text-white"  style="height: 40px; width: 120px;"> Logout </a>
          </div>

        </div>
      </div>

      <!-- img -->
      <div class="col-6 d-flex justify-content-end">
        <div class="">
          <img src="{%static 'img/header.png'%}" width="380px" class="">
        </div>
      </div>
    </div>

    <!-- isi -->
    <div class="container py-5 text-center container">
      <!-- sweet alert -->
      {%for message in messages%}
      {% if message.tags == 'success' %}                     
      <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>                                            
      <script>
          var m="{{message}}";
          swal("Absen",m,"success");
      </script>
      {% endif %}
      {%endfor%}

      <h1 class="fw-light">Riwayat Absensi Anda</h1> 
      <!-- jumlah -->
      <div class="container mt-3">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3  bg-primary">
                <h4 class="my-0 fw-bold text-white">Hadir</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{jlh_hadir}}<small class="text-muted fw-light">x</small></h1>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3  bg-warning">
                <h4 class="my-0 fw-bold text-white">PULANG</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{jlh_pulang}}<small class="text-muted fw-light">x</small></h1>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3  bg-success">
                <h4 class="my-0 fw-bold text-white">IZIN</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{jlh_izin}}<small class="text-muted fw-light">x</small></h1>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- tabel -->
      <div class="container mt-4">
        <table class="table table-bordered align-middle able-responsive">
          <thead class="table-dark">
            <tr>
              <th>NO</th>
              <th>TANGGAL</th>
              <th>WAKTU</th>
              <th>STATUS</th>
              <!-- <th>KETERANGAN</th> -->
            </tr>
          </thead>
          <tbody>
            {%for data in datas.object_list%}
            <tr>
              <td>{{forloop.counter}}</td>                      
              <td>{{data.tgl}}</td>
              <td>{{data.waktu}}</td>
              <td>{{data.status}}</td>
              <!-- <td class="text-start">{{data.ket}}</td> -->
            </tr>
            {%endfor%}
          </tbody>
        </table>
        <!-- paginations -->
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {%for data in datas.paginator.page_range%}
              {%if datas.number == data %}
              <li class="page-item active">
                <a class="page-link" href="{%url 'akun'%}?page={{data}}">{{data}}</a>
              </li>
              {%else%}
              <li class="page-item">
                <a class="page-link" href="{%url 'akun'%}?page={{data}}">{{data}}</a>
              </li>
              {%endif%}
            {%endfor%}
          </ul>
        </nav>

      </div>
    </div>

    <!-- footer -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top text-white" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

absen_SQLite/templates/index.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">

    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- absencss -->
    <link rel="stylesheet" href="{%static 'css/absen.css'%}">
    <title>AbsensiOnline | Home </title>
  </head>
  <body style="background-color: rgb(3, 3, 160);">

    <!-- HEADER -->
    <div class="row " style="margin-bottom:280px;">
      <!--  KOLOM 1 MENU HEADER -->
      <div class="col-8">
        <div class="container text-white pt-4">
          <div class="head px-5 pt-5" style="margin: 50px auto;" >
            <h1 class="" style="font-size:5vw">Selamat Datang! </h1>
            <h3 class="absen" style="font-size:60px; color: rgb(237, 100, 166);">Absensi Karyawan<span style="text-decoration: none; color: white;">Online</span></h3>
            <p class="pe-5">Lorem ipsum dolor sit amet, consectetur facilis adipisicing elit 
              accusantium,Lorem ipsum <br> dolor sit amet, consectetur saepe dignissimos a ut ex facilis inventore! <br>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit 
            
            </p>
            <a href="{%url 'absen:login'%} " class="btn btn-primary" style="height: 40px; width: 120px;"> Login </a>
            <a href="{% url 'absen:register'%}" class="btn btn-outline-primary text-white"  style="height: 40px; width: 120px;"> Register </a>
          </div>

        </div>
      </div>

      <!--KOLOM 2 GAMBAR HEADER-->
      <div class="col-4 d-flex justify-content-end">
        <div class="">
          <img src="{%static 'img/header.png'%}" width="380px" class="">
        </div>
      </div>

    </div>
    <!-- AKHIR HEADER -->

    <!-- FOOTER -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center text-white" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 
    <!-- AKHIR FOOTER -->


    <!-- JAVASCRIPT -->
    <script src="{%static 'js/bootstrap.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
  </body>
</html>