absens_MYSQL/absen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

# gambar/static
from django.conf import settings 
from django.conf.urls.static import static 

#url/alamat per halaman 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='home'),
    path('akun',views.akun, name='akun'),
    path('absen/',include('absenapp.urls', namespace='absen'  ) ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

absens_MYSQL/absenapp/urls.py
from django.urls import path
from . import views

# utntuk menyambungkan/include url pada menu/app dengan project
app_name='absenapp'

#url/alamat per halaman 
urlpatterns =[
    path('',views.absen, name='absen'),
    path('profile/',views.profile, name='profile'),
    path('register/',views.register, name='register'),
    path('login/',views.loginAkun, name='login'),
    path('logoutAkun/',views.logoutAkun, name='logout'),
]

absens_MYSQL/absenapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# tabel untuk profile karyawan
class profil(models.Model):
    nama        =models.OneToOneField(User, on_delete=models.CASCADE, related_name='profil')
    nip         =models.CharField(max_length=50, default='-')
    jk =(
        ('Laki-Laki','L'),
        ('Perempuan','P'),
    )
    jenisK      =models.CharField(choices=jk, max_length=10)
    jabatan     =models.CharField(max_length=50,null=True)
    alamat      =models.TextField()
    

    def __str__(self):
        return "{}".format(self.nama)

# tabel utnuk absen karyawan
class absenModel(models.Model):
    # data karyawan    
    pegawai     =models.ForeignKey(profil, on_delete=models.DO_NOTHING)
    tgl         =models.DateField(auto_now_add=True)
    waktu       =models.TimeField(auto_now_add=True)
    absen=(
        ('HADIR','HADIR'),
        ('IZIN','IZIN'),
        ('PULANG','PULANG'),
    )
    status      =models.CharField(choices=absen, max_length=50, default='HADIR')
    ket         =models.TextField(null=True, blank=True) 

    def __str__(self):
        return "{},{}".format(self.pegawai,self.status)

absens_MYSQL/absenapp/forms.py
from django import forms
from . models import absenModel,profil

# form untuk profil karyawan
class profilForm(forms.ModelForm):
    class Meta():
        model=profil #nama tabel
        fields="__all__" #ambil semu kolom
        
        # untuk merubah/ganti nama label 
        labels= {
            'jenisK' : 'Jenis Kelamin',
        }

        # untuk styling form
        widgets={
            'nama':forms.Select(
                attrs={
                    'class':'form-control',}
                ),
            'nip':forms.TextInput(
                attrs={
                    'class':'form-control',}
                ),
            'jenisK':forms.Select(
                attrs={
                    'class':'form-control',
                    'label':'Jenis Kelamin'}
                ),
            'jabatan':forms.TextInput(
                attrs={
                    'class':'form-control',}
                ),
            'alamat':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'style':'height: 80px;',}
                ),
            }

# form untuk absen
class absenForm(forms.ModelForm):
    class Meta:
        model = absenModel
        fields = [
                'pegawai',
                'status',
                'ket',      
            ]
        widgets={
            'pegawai':forms.Select(
                attrs={
                    'value':'{{user}}',
                    'class':'form-control',}
                ),
            'status':forms.Select(
                attrs={
                    'class':'form-control',}
                ),
            'ket':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'style':'height: 80px;',}
                ),
            }

absens_MYSQL/absen/views.py
from django.shortcuts import render,redirect
from absenapp . models import absenModel,profil
from django.contrib.auth import authenticate

def akun(request):
    # ambil nama berdasarkan user yang aktif dari tabel profil -> (1 jenis data yaitu nama)
    profile=profil.objects.get(nama=request.user)

    # ambil data pegawai berdasarkan user yang aktif (profil) dari tabel absenmodel ->(semua data)
    datas= absenModel.objects.filter(pegawai=profile)
    
    # inisialiasi jumlah status: hadir,izin dan pulang
    jh=0
    ji=0
    jp=0
    # untuk mendaptkan jumlah sesuai status maka setiap kali melakukan absen akan di jumlahkan sesuai dengan statusnya
    for jlh in datas:
        if jlh.status == 'HADIR': #jika status absennya hadir maka variabel inisialisasi kita jumlahkan
            jh += 1
        elif jlh.status == 'IZIN':
            ji += 1
        elif jlh.status == 'PULANG':
            jp += 1
        else:
            pass

    context = {
        'datas':datas,
        'jlh_hadir':jh,
        'jlh_izin':ji,
        'jlh_pulang':jp,
    }

    return render(request,'akun.html',context)

def index(request):

    return render(request, 'index.html')

absens_MYSQL/absenapp/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from absenapp . models import absenModel,profil
from .forms import profilForm,absenForm


@login_required() #fungsi ini bisa diakses setelah login berhasil
def absen(request):
    data = absenModel.objects.all() #ambil semua data di tabel absenmodel
    
    ab = absenForm(request.POST or None) #inisial request 
    if request.method == 'POST':
        if ab.is_valid(): #jika isi form valid
            ab.save()  #simpan semua isi form
        return redirect('akun') #setelah disimpan, kemudian arahkan ke alamat/url akun
        
    #lempar data yang sudah didapat ke templates
    context = { 
        'profile':ab,
        'datas':data,
    }
    return render(request, 'absen.html',context)

@login_required()
def profile(request):

    karyawan=profilForm(request.POST or None)
    if request.method == 'POST':
        if karyawan.is_valid():
            karyawan.save()
        return redirect('absen:absen')

    context = {
        'karyawan':karyawan,
    }
    return render(request,'profile.html', context)

# AKUN
def register(request):
    if request.method=='POST':
        username=request.POST.get('username') #megambil data dari form username
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')

        if pass1!=pass2: #jika password/password 1 tidak sama dengan confirm password atau password ke 2
            return HttpResponse("Mohon maaf🙏🏻..Password tidak Sama!!") 
        else: #jika sama password 1 dengan ke 2
            my_user=User.objects.create_user(username,email,pass1) #buat user baru dengan data username,email dan password
            my_user.save()
            return redirect('absen:login') #ke halaman login

    return render(request,'register.html')

def loginAkun(request):
    if request.method=='POST':
        username=request.POST.get('username')
        pass1=request.POST.get('passw')

        user=authenticate(request,username=username,password=pass1) #cek username dan password
        if user is not None: #jika username dan password ada di database maka
            login(request, user) #login berhasil
            if user.is_superuser: #jika user adalah admin maka tampilkan halaman admin
                return redirect('/admin/')
            else: #jika user bukan admin maka tampilkan halaman absen
                return redirect('absen:profile')
        else:# jika username dan password  tidak ada
            # return HttpResponse ("Mohon maaf🙏🏻..Username dan Password tidak Valid!!")
            return redirect('absen:login') #ke halaman login
    return render(request,'login.html')

def logoutAkun(request):
    logout(request) 
    return redirect('absen:login')

absens_MYSQL/templates/absen.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">
    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <title>AbsensiOnline</title>
  </head>
  <body>
    <div class="row" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
        <div class="container py-5 text-center">
            <div class="row">
                <div class="col-12">
                    <div class="row py-lg-5">
                        <div class="col-lg-6 col-md-8 mx-auto">
                            <div class="card">
                                <div class="card-body py-4 px-md-5" style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                                    <form class="my-3" method="POST" >
                                      {%csrf_token%}                                       
                                        <div class="row">
                                        <div class="col-12 mb-4">
                                            <div class="form-outline text-center">
                                            <h1>Hai...👋🏻{{user}}, Absen!</h1>
                                            <h6 id="waktu"></h6>                                                                                                          
                                          </div>
                                        </div>                         
                                        </div>

                                        <!-- Email input -->
                                        {%for form in profile %}
                                        <div class="form-group form-outline mb-4 text-start">
                                            {{form.label}}
                                            {{form}}
                                        </div>
                                        {%endfor%}
        
                                        <!-- Submit button -->
                                        <button type="submit" class="btn btn-primary mb-4" style="width: 100%;" >
                                        Absen
                                        </button>

                                        <!-- Register buttons -->
                                        <div class="text-center">
                                        <p>Kembali ke halaman<a href="{%url 'absen:profile'%}" class="text-primary">Profile</a></p>
                                        <a href="/" class="text-dark" style="text-decoration: none;">Kembali ke Halaman <span class="fw-bold">Home</span></a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-5 text-white" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 

    <!-- waktu -->
    <script>
      let waktu = document.getElementById("waktu");
      setInterval(() => {
          let jam  = new Date();
          waktu.innerHTML = jam.toLocaleTimeString();
        },100
      )
     
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{%static 'js/bootstrap.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
  </body>
</html>

absens_MYSQL/templates/akun.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">
    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <title>AbsensiOnline | Absen </title>
  </head>
  <body>
    <!-- header -->
    <div class="row" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-6">
        <div class="container text-white pt-4" style="height: 450px;">
          <div class="head ps-5 pt-5" style="margin: 50px auto;" >
            <h1 class=""> Hai...👋🏻<a class="text-primary" href="/" style="text-decoration: none;">{{user}}</a> Selamat Datang</h1>
            <p class="pe-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.Blanditiis corporis, adipisci  
              accusantium,Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>
              saepe dignissimos a ut ex facilis inventore!</p>
            <a href="{%url 'absen:absen'%} " class="btn btn-primary" style="height: 40px; width: 120px;"> Absensi </a>
            <a href="{% url 'absen:logout'%}" class="btn btn-outline-primary text-white"  style="height: 40px; width: 120px;"> Logout </a>
          </div>

        </div>
      </div>

      <!-- img -->
      <div class="col-6 d-flex justify-content-end">
        <div class="">
          <img src="{%static 'img/header.png'%}" width="380px" class="">
        </div>
      </div>
    </div>

    <!-- isi -->
    <div class="container py-5 text-center container">
      <h1 class="fw-light">Riwayat Absensi Anda</h1> 
      <!-- jumlah -->
      <div class="container mt-3">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3  bg-primary">
                <h4 class="my-0 fw-bold text-white">Hadir</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{jlh_hadir}}<small class="text-muted fw-light">x</small></h1>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3  bg-warning">
                <h4 class="my-0 fw-bold text-white">PULANG</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{jlh_pulang}}<small class="text-muted fw-light">x</small></h1>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3  bg-success">
                <h4 class="my-0 fw-bold text-white">IZIN</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{jlh_izin}}<small class="text-muted fw-light">x</small></h1>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- tabel -->
      <div class="container mt-4">
        <table class="table table-bordered align-middle able-responsive">
          <thead class="table-dark">
            <tr>
              <th>NO</th>
              <th>TANGGAL</th>
              <th>WAKTU</th>
              <th>STATUS</th>
              <!-- <th>KETERANGAN</th> -->
            </tr>
          </thead>
          <tbody>
            {%for data in datas%}
            <tr>
              <td>{{forloop.counter}}</td>                      
              <td>{{data.tgl}}</td>
              <td>{{data.waktu}}</td>
              <td>{{data.status}}</td>
              <!-- <td class="text-start">{{data.ket}}</td> -->
            </tr>
            {%endfor%}
          </tbody>
        </table>
      </div>
    </div>

    <!-- footer -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top text-white" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

absens_MYSQL/templates/index.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">

    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- absencss -->
    <link rel="stylesheet" href="{%static 'css/absen.css'%}">
    <title>AbsensiOnline | Home </title>
  </head>
  <body style="background-color: rgb(3, 3, 160);">

    <!-- HEADER -->
    <div class="row " style="margin-bottom:280px;">
      <!--  KOLOM 1 MENU HEADER -->
      <div class="col-8">
        <div class="container text-white pt-4">
          <div class="head px-5 pt-3" style="margin: 50px auto;" >
            <h1 class="" style="font-size:5vw">Selamat Datang! </h1>
            <h3 class="absen" style="font-size:60px; color: rgb(237, 100, 166);">Absensi Karyawan<span style="text-decoration: none; color: white;">Online</span></h3>
            <p class="pe-5">Lorem ipsum dolor sit amet, consectetur facilis adipisicing elit 
              accusantium,Lorem ipsum <br> dolor sit amet, consectetur saepe dignissimos a ut ex facilis inventore! <br>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit 
            
            </p>
            <a href="{%url 'absen:login'%} " class="btn btn-primary" style="height: 40px; width: 120px;"> Login </a>
            <a href="{% url 'absen:register'%}" class="btn btn-outline-primary text-white"  style="height: 40px; width: 120px;"> Register </a>
          </div>

        </div>
      </div>

      <!--KOLOM 2 GAMBAR HEADER-->
      <div class="col-4 d-flex justify-content-end">
        <div class="">
          <img src="{%static 'img/header.png'%}" width="380px" class="">
        </div>
      </div>

    </div>
    <!-- AKHIR HEADER -->

    <!-- FOOTER -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center text-white py-3" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 
    <!-- AKHIR FOOTER -->


    <!-- JAVASCRIPT -->
    <script src="{%static 'js/bootstrap.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
  </body>
</html>

absens_MYSQL/templates/login.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">
    <title>AbsensiOnline | Login</title>
  </head>
  <body style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
    <div class="container">
        <!-- login -->
        <section class=" my-5">
          <div class="px-4 py-5 px-md-5 text-center text-lg-start" style="background-color: hsl(0, 0%, 96%); box-shadow: rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;">
            <div class="container">
              <div class="row gx-lg-5 align-items-center">
                <!-- kolom 1 kiri keterangan  -->
                <div class="col-lg-6 mb-5 mb-lg-0">
                  <h1 class="mb-2 display-3 fw-bold ls-tight">
                    Login Absensi <span class="text-primary">Online</span>
                  </h1>
                  <p style="color: hsl(217, 10%, 50.8%)">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, itaque accusantium odio, soluta, corrupti aliquam
                    quibusdam tempora at cupiditate quis eum maiores libero
                    veritatis? Dicta facilis sint aliquid ipsum atque?
                  </p>
                
                </div>
                
                <!-- kolom 2 kanan form -->
                <div class="col-lg-6 mb-5 mb-lg-0">
                  <div class="card">
                    <div class="card-body py-4 px-md-5" style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                      <form class="my-3" method="POST" >
                        {%csrf_token%}
                        <!-- 2 column grid layout with text inputs for the first and last names -->
                        <div class="row">
                          <div class="col-12 mb-4">
                            <div class="form-outline text-center">
                              <h1>Login</h1>
                              <p>sebelum absen silahkan login terlebih dahulu!</p>
                            </div>
                          </div>                         
                        </div>

                        <!-- username input -->
                        <div class="form-outline mb-4">
                          <label class="form-label" for="username">Username</label>
                          <input type="text" placeholder="Enter Username" id="username" name="username" class="form-control " />
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-4">
                          <label class="form-label">Password</label>
                          <input type="password" placeholder="Password" id="password" name="passw" class="form-control" />
                        </div>
                    
                        <!-- Submit button -->
                        <button type="submit" class="btn btn-primary mb-4" style="width: 100%;" >
                          Login
                        </button>

                        <!-- Register buttons -->
                        <div class="text-center">
                          <p>Sudah punya akun?<a href="{%url 'absen:register'%}" class="text-primary">Daftar</a></p>
                          <a href="/" class="text-dark" style="text-decoration: none;">Kembali ke Halaman <span class="fw-bold">Home</span></a>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>

        </section>
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

absens_MYSQL/templates/profile.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet">
    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <title>AbsensiOnline</title>
  </head>
  <body>
    <div class="row" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
        <div class="container py-5 text-center">
            <div class="row">
                <div class="col-12">
                    <div class="row py-lg-5">
                      <!-- kolom 1 tengah profile -->
                        <div class="col-lg-6 col-md-8 mx-auto">
                            <div class="card">
                                <div class="card-body py-4 px-md-5" style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                                    <form class="my-3" method="POST" >
                                      {%csrf_token%}
                                        <!-- 2 column grid layout with text inputs for the first and last names -->
                                        <div class="row">
                                        <div class="col-12 mb-4">
                                            <div class="form-outline text-center">
                                            <h1>Profile</h1>
                                            <h6>silahkan lengkapi profil anda terlebih dahulu!</h6>                                                                   
                                            </div>
                                        </div>                         
                                        </div>                                      

                                        <!-- PROFILE input -->
                                        <div class="row">
                                        <div class="col-12">
                                          {%for form in karyawan %}
                                          <div class="form-group form-outline mb-4 text-start">
                                              {{form.label}}
                                              {{form}}
                                          </div>
                                          {%endfor%}
                                        </div>                     
                                       </div> 
                                                    
                                        <!-- Submit button -->
                                        <button type="submit" class="btn btn-primary mb-4" style="width: 100%;" >
                                        Simpan
                                        </button>

                                        <!-- Register buttons -->
                                        <div class="text-center">
                                        
                                        <p>Sudah isi profile?<a href="{%url 'absen:absen'%}" class="text-primary">Lewati</a></p>
                                        <a href="/" class="text-dark" style="text-decoration: none;">Kembali ke Halaman <span class="fw-bold">Home</span></a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-5 text-white" style="background-image: linear-gradient(to right,  rgb(11, 11, 138),rgb(3, 3, 83));">
      <div class="col-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2023 Elcoder, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ">
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-facebook"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i width="24" height="24" class="bi bi-instagram"></i></a></li>
      </ul>
    </footer> 

    <!-- waktu -->
    <script>
      let waktu = document.getElementById("waktu");
      setInterval(() => {
          let jam  = new Date();
          waktu.innerHTML = jam.toLocaleTimeString();
        },100
      )
     
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>